### ISSUE TITLE
fit tooltip width to images

### ISSUE THREAD

**Issue by micahstubbs** [MasonChinkin/MasonChinkin.github.io#1]
fit tooltip width to images

![screen shot 2018-07-02 at 7 47 41 pm](https://user-images.githubusercontent.com/2119400/42196090-e1b24952-7e30-11e8-8068-4036afcc4598.png)

**Comment by micahstubbs** [comment]
really like the travel map!   you already some nice tooltips, so I feel like they deserve the extra polish of full-width images 😄 (or narrow tooltips fit to the width of the existing image)

**Comment by MasonChinkin** [comment]
bam

**Comment by MasonChinkin** [comment]
That one damn sagrada familia pic is such a different orientation from the rest...I might just change the pic to make life easier.

**Comment by micahstubbs** [comment]
changing the content is a perfectly valid way to solve the problem (especially when you control the content) 😄
