### ISSUE TITLE
collapsible sidebar

### ISSUE THREAD

**Issue by micahstubbs** [MasonChinkin/MasonChinkin.github.io#3]
collapsible sidebar

![screen shot 2018-07-02 at 7 51 00 pm](https://user-images.githubusercontent.com/2119400/42196240-c6c6a54c-7e31-11e8-9ead-e1d73d602dde.png)

**Comment by micahstubbs** [comment]
this feature is not strictly necessary for the page, but it's a nice learning experience to figure out how to implement it.  most apps with a sidebar like this will want that feature.

a starting point https://stackoverflow.com/questions/30574902/collapsible-flexible-width-sidebar-using-only-css

**Comment by MasonChinkin** [comment]
Wow this change was a huge improvement. By collapsing the sidebar and setting the width of my visualizations to the div the whole site looks much more uniform and professional. It also forced me to learn a lot about the underlying HTML5 UP format that I used for the site.

**Comment by micahstubbs** [comment]
it does look really nice now

![screen shot 2018-07-03 at 5 16 17 pm](https://user-images.githubusercontent.com/2119400/42250266-d1221b3a-7ee4-11e8-9f0c-37f3be903b28.png)

**Comment by micahstubbs** [comment]
and yea, being able to hack someone else's HTML + CSS layout is a very useful skill
